#pragma once

#include <Windows.h>
#include <wchar.h>

// MAME/Supermodel-only configuration bootstrap.
//
// The original plugin expects FFBPlugin.ini to exist before most of its
// file-scope settings are initialized. This wrapper keeps that behaviour,
// but creates a MAME configuration automatically when the INI is missing.
// Existing INIs are never overwritten. Auto-generated INIs are only filled
// with missing keys, so user changes remain untouched.
namespace MAMESupermodelAutoIni
{
	static const wchar_t* const kIniPath = L".\\FFBPlugin.ini";

	inline bool StartsWith(const wchar_t* value, const wchar_t* prefix)
	{
		if (!value || !prefix)
			return false;

		const size_t prefixLength = wcslen(prefix);
		return wcsncmp(value, prefix, prefixLength) == 0;
	}

	inline bool IsOurIni(const wchar_t* fileName)
	{
		return fileName && lstrcmpiW(fileName, kIniPath) == 0;
	}

	inline bool IsSettingsSection(const wchar_t* section)
	{
		return section && lstrcmpiW(section, L"Settings") == 0;
	}

	inline void EnsureIniExists()
	{
		const DWORD attributes = GetFileAttributesW(kIniPath);
		if (attributes != INVALID_FILE_ATTRIBUTES)
			return;

		// Keep the initial file deliberately small. Integer settings are added
		// automatically by ReadPrivateProfileInt() when the plugin reads them.
		static const char initialIni[] =
			"; Auto-generated by the MAME/Supermodel FFB Plugin\r\n"
			"; Existing values are never overwritten by the plugin.\r\n"
			"\r\n"
			"[Settings]\r\n"
			"AutoGenerated=1\r\n"
			"GameId=22\r\n"
			"StartDelay=0\r\n"
			"DeviceGUID=\r\n"
			"Device2GUID=\r\n"
			"Device3GUID=\r\n";

		HANDLE file = CreateFileW(
			kIniPath,
			GENERIC_WRITE,
			FILE_SHARE_READ,
			nullptr,
			CREATE_NEW,
			FILE_ATTRIBUTE_NORMAL,
			nullptr);

		if (file == INVALID_HANDLE_VALUE)
			return;

		DWORD bytesWritten = 0;
		WriteFile(file, initialIni, static_cast<DWORD>(sizeof(initialIni) - 1), &bytesWritten, nullptr);
		CloseHandle(file);
	}

	inline bool IsAutoGeneratedIni()
	{
		return GetPrivateProfileIntW(L"Settings", L"AutoGenerated", 0, kIniPath) == 1;
	}

	inline bool HasKey(const wchar_t* section, const wchar_t* key, const wchar_t* fileName)
	{
		static const wchar_t missingMarker[] = L"__FFBPLUGIN_MISSING__";
		wchar_t value[64] = {};

		GetPrivateProfileStringW(section, key, missingMarker, value, 64, fileName);
		return wcscmp(value, missingMarker) != 0;
	}

	// These are the MAME defaults we currently ship/use. Most values already
	// match the defaults in MAMESupermodel.cpp; only the historical/tuned MAME
	// values that differ need special handling here.
	inline int GetMameDefault(const wchar_t* key, int fallback)
	{
		if (!key)
			return fallback;

		if (wcscmp(key, L"GameId") == 0)
			return 22;

		if (wcscmp(key, L"StartDelay") == 0)
			return 0;

		// MAME output builds historically use 500 ms as their standard command
		// length, while several old code fallbacks still say 120.
		if (StartsWith(key, L"FeedbackLength"))
			return 500;

		// The left alternative force is negative in the generated MAME INI.
		if (StartsWith(key, L"AlternativeMaxForceLeft"))
		{
			if (wcscmp(key, L"AlternativeMaxForceLeftSuperChase") == 0)
				return -80;
			return -100;
		}

		// Generic MAME spring strength is 100. Per-game spring defaults are 80.
		if (wcscmp(key, L"ForceSpringStrength") == 0)
			return 100;
		if (StartsWith(key, L"ForceSpringStrength"))
			return 80;

		// Sega scaler / rumble defaults used by the MAME output configuration.
		if (StartsWith(key, L"SinePeriod"))
			return 100;
		if (StartsWith(key, L"SineStrength"))
			return 100;
		if (StartsWith(key, L"RumbleStrengthLeftMotor"))
			return 100;
		if (StartsWith(key, L"RumbleStrengthRightMotor"))
			return 100;

		// Existing tuned exceptions from the MAME configuration.
		if (wcscmp(key, L"MaxForceSuperChase") == 0)
			return 80;
		if (wcscmp(key, L"AlternativeMaxForceRightSuperChase") == 0)
			return 80;
		if (wcscmp(key, L"FFBDivideDirtDash") == 0)
			return 1913;
		if (wcscmp(key, L"FFBDivideAceDriverVictory") == 0)
			return 643;
		if (wcscmp(key, L"FFBDivideAceDriver") == 0)
			return 643;
		if (wcscmp(key, L"FFBGainCrusnExotica") == 0)
			return 400;

		return fallback;
	}

	inline UINT ReadPrivateProfileInt(
		LPCWSTR section,
		LPCWSTR key,
		INT defaultValue,
		LPCWSTR fileName)
	{
		if (!IsOurIni(fileName) || !IsSettingsSection(section))
			return GetPrivateProfileIntW(section, key, defaultValue, fileName);

		EnsureIniExists();

		const bool autoGenerated = IsAutoGeneratedIni();
		int effectiveDefault = defaultValue;

		// A missing GameId must still dispatch to MAMESupermodel. Other custom
		// defaults are only applied to INIs generated by this bootstrap, so a
		// hand-written/existing INI keeps its old fallback behaviour.
		if (key && wcscmp(key, L"GameId") == 0)
			effectiveDefault = 22;
		else if (autoGenerated)
			effectiveDefault = GetMameDefault(key, defaultValue);

		if (autoGenerated && !HasKey(section, key, fileName))
		{
			wchar_t value[32] = {};
			wsprintfW(value, L"%d", effectiveDefault);
			WritePrivateProfileStringW(section, key, value, fileName);
		}

		return GetPrivateProfileIntW(section, key, effectiveDefault, fileName);
	}
}

// DllMain.cpp and MAMESupermodel.cpp both include MAMESupermodel.h before
// reading their INI integers. Redirect only those subsequent profile-int
// reads through the MAME bootstrap without touching the rest of the plugin.
#ifdef GetPrivateProfileInt
#undef GetPrivateProfileInt
#endif
#define GetPrivateProfileInt MAMESupermodelAutoIni::ReadPrivateProfileInt
